name: run-tests

on: [push, pull_request, workflow_dispatch]

jobs:
    tests:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                php: [8.0, 8.1]
                laravel: [8.*, 9.*, 10.*]
                dependency-version: [prefer-lowest, prefer-stable]
                include:
                    - laravel: 10.*
                      testbench: 8.*
                    - laravel: 9.*
                      testbench: 7.*
                    - laravel: 8.*
                      testbench: 6.*
                exclude:
                   # excludes laravel 10 on php7.4, php 8.0
                    - php: 7.4
                      laravel: 10.*
                    - php: 8.0
                      laravel: 10.*
                    # excludes laravel 9 on php7.4
                    - php: 7.4
                      laravel: 9.*
                    # excludes laravel 7 on php8
                    - php: 8.0
                      laravel: 7.*
                    # excludes laravel 7+8 on php8.1
                    - php: 8.1
                      laravel: 7.*
                    - php: 8.1
                      laravel: 8.*

        name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install SQLite 3
              run: |
                  sudo apt-get update
                  sudo apt-get install sqlite3
                  sudo apt-get install redis
            - name: Cache dependencies
              uses: actions/cache@v2
              with:
                  path: ~/.composer/cache/files
                  key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: curl, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, iconv, redis
                  coverage: none

            - name: Install dependencies
              run: |
                  composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
                  composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest
            - name: Execute tests
              run: vendor/bin/phpunit tests
